# Generated by Django 5.0.6 on 2024-07-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_file',
            field=models.FileField(default=1, upload_to='videos'),
            preserve_default=False,
        ),
    ]
