# Generated by Django 5.0.6 on 2024-07-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='until_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
