# Generated by Django 5.0.6 on 2024-07-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_until_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
