# Generated by Django 5.0.6 on 2024-08-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment_dislikes_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_negative',
            field=models.BooleanField(default=False),
        ),
    ]
